import { defineConfig } from 'vitest/config'
import path from 'path'

export default defineConfig({
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
  test: {
    setupFiles: ['src/__tests__/setup.ts'],
    environment: 'jsdom',
    include: ['src/**/__tests__/**/*.test.{ts,tsx}'],
    coverage: {
      provider: 'v8',
      include: [
        'src/lib/validations/**',
        'src/lib/utils/timezone.ts',
        'src/lib/utils/position-slots.ts',
        'src/lib/utils/schedule-label.ts',
        'src/lib/utils/pricing.ts',
        'src/lib/utils/registration-positions.ts',
        'src/lib/services/guest-user.ts',
        'src/lib/errors/messages.ts',
        'src/lib/constants/labels.ts',
        'src/lib/config/branding.ts',
        'src/lib/config/extraction-settings.ts',
        'src/lib/hooks/useSupabaseQuery.ts',
        'src/lib/hooks/useCrudDialog.ts',
        'src/lib/hooks/usePagination.ts',
        'src/lib/hooks/useCurrentUser.ts',
        'src/components/app-shell.tsx',
        'src/components/public-calendar.tsx',
        'src/components/position-modal.tsx',
        'src/lib/middleware/profile-cache.ts',
        'src/middleware.ts',
        'src/app/api/registrations/counts/route.ts',
        'src/app/api/registrations/by-position/route.ts',
        'src/app/api/profile/complete/route.ts',
        'src/app/api/users/search/route.ts',
        'src/app/api/users/[userId]/ban/route.ts',
        'src/app/api/register/group/route.ts',
        'src/app/api/admin/register/route.ts',
        'src/app/api/admin/payments/schedules/route.ts',
        'src/app/api/admin/payments/[id]/route.ts',
        'src/app/api/scanner/scan/route.ts',
        'src/app/api/scanner/schedules/route.ts',
        'src/app/api/scanner/schedules/[scheduleId]/players/route.ts',
        'src/lib/hooks/useSchedulesForScanner.ts',
        'src/lib/hooks/useSchedulePlayers.ts',
      ],
      reporter: ['text', 'html'],
      thresholds: { lines: 90, functions: 90, branches: 85 },
    },
  },
})
